### ISSUE TITLE
Create a spreadsheet with a list of organizations to test the script out with

### ISSUE THREAD

**Issue by mayawagon** [opentechinstitute/990-scraper#2]

**Comment by mayawagon** [comment]
Here you go: https://docs.google.com/spreadsheets/d/1FHcZ9xL3CJ5OWQEj1MbsbUa1oUpgFdjtBjAaXacJMsQ/edit?usp=sharing

**Comment by drewrwilson** [comment]
Here's a testing spreadsheet I'm using to write the EIN query functions. Only test data in it

https://docs.google.com/spreadsheets/d/14qmY3F3sSJ85aJMuzdIHR_mzVRsdCbtPjBgryNWIJcs/edit?usp=sharing

**Comment by drewrwilson** [comment]
a list of like 20-400 nonprofit EINs would be real helpful

**Comment by ivarthorson** [comment]
Hi from Oregon! There are downloadable sets of data at:
https://data.oregon.gov/Business/Active-Nonprofit-Corporations/8kyv-b2kw
There are 150k of them, and they have JSON and CSV formats.
